language: node_js
node_js:
- '0.10'
env:
  global:
  - secure: UmeSAqP7p6o9Bdb6y5UHtu+Hbn+X+ZxD16HUO7v5U4csZnUQpWvA7YEjcIlNucdJ6zdipURAF6WY9XGd1D8VgW/kWzKJnUtamUTr+tBJdZ3CR91uuD93ycAlKu9SLctlpFGRx/01pryAZ3E1mBgVARMOmSEeLS1kDKL8ZCut9z0=
  - secure: fzaUm/ByTY97Uk6ihtfvsJBcwgXD62IRQGplTTlvaFOZsrstcWQN77ZfOy9Kb/9kPaHDT8qLKopEgHrXFxLvCzfMuUotzKxBLTeaWnZkdZFpRx/9Ps0UIamGP5gEBKPvcT6Nljl+KSQfie0NBgJLqAhLUTQOwIcKqwiIxuTl9kA=
  - secure: ZOttTKU5Rotw7fYkD8wvccdxgY0IDoeIkZ9+egecCrs6EUzNkCqV2Hros+28x9qT723MW38fq85QBzGB+lKRi6j37pUyhTwpj6KWEMoho7xD/r/LvTTcSWwFcSGClRhpt2wClazYPWtDemSzEsZe6BmYcqbunSFK2UUPFBdKWkk=
addons:
  ssh_known_hosts:
  - 128.199.54.7
script: ./node_modules/.bin/gulp
branches:
  only:
  - master
after_success:
- sudo apt-get -y -qq install sshpass
- rsync -arlptzO --delete --stats --rsh="sshpass -p $DEPLOY_PASSWORD ssh -l $DEPLOY_USER" ./out/web/ 128.199.54.7:$DEPLOY_DEST
