language: node_js
node_js:
- '0.10'
env:
  global:
  - secure: PbVqot8Sxfn+2nxkUvV8p1KRSWNACLvu3ec+eg5bYGAXbrx3Gx1FzfGh5jWmmD5E12f+FGM5RAyHUvKxq5xT6YQctkphfnmHUSYyyF+JYZGSy7S6czkiyTEKA/Cv5OC8lVispffNl2bDdLg/VUZxywqlxUymchjy2gFiI+Gev6A=
  - secure: dzorcw29qIlRvCk0rUaf5uQfAgEqHSjYB6NcF10ZvgdjhFlQiVOhAeJSfeZDYf3/4bf/stPXDLgF/pgokMXaUr8WDRJyX3tNkWv8l9G8PKfstd0xdOvIDaw6JfKENUz29tQRWbCSW4rShtzFn4WHoae0Va24frNDB8RFGTOdzTA=
branches:
  only:
    - master
after_success:
  - chmod 600 .travis/deploy_key.pem
  - ssh-add .travis/deploy_key.pem
  - scp -oStrictHostKeyChecking=no -i .travis/deploy_key.pem -r ./out/web $DEPLOY_USER@emmet.io:$DEPLOY_PATH
